[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"
  publish = "."
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # GitHub token will be set in Netlify UI
  # GITHUB_TOKEN = "xxx"
